[tool.poetry]
name = "hw-lint-v2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
requests = "^2.34.2"
environs = "^15.0.1"
python-dotenv = "^1.2.2"
pandas = "^3.0.3"
openpyxl = "^3.1.5"
pandas-stubs = "^3.0.3.260530"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
mypy = "^2.1.0"
black = "^26.5.1"
isort = "^8.0.1"
pytest = "^9.0.3"
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
